files = [
#"wrsw_hsr_lre.vhd",
"wrsw_hsr_lre_pkg.vhd",
"xhsr_tagger.vhd",
"xhsr_untagger.vhd",
"xhsr_dropper.vhd",
"xhsr_dropper_mem.vhd",
"hsr_lre_dropper_regs.vhd",
"hsr_lre_dropper_regs_pkg.vhd",
"xwrsw_hsr_lre.vhd",
"wrsw_hsr_junction.vhd",
"wrsw_hsr_arbfromtaggers.vhd",
"xhsr_fwd.vhd",
"xhsr_mux.vhd",
"xhsr_seq.vhd",
"hsr_lre_regs.vhd",
"hsr_lre_regs_pkg.vhd"]
